version: "3.1"

volumes:
  postgres:

services:
  postgres:
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "helloWRLD"
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    restart: always
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
#    environment:
#      SPRING_DATASOURCE_URL: 'jdbc:postgresql://postgres:5432/postgres'
#      SPRING_DATASOURCE_USERNAME: 'postgres'
#      SPRING_DATASOURCE_PASSWORD: 'helloWRLD'
#      SPRING_DATASOURCE_DRIVER_CLASS_NAME: 'org.postgresql.Driver'
