version: "3.1"

volumes:
  postgres:

services:
  postgres:
    image: postgres:13.3
    restart: always
    env_file:
      - src/main/resources/secret.env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    restart: always
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - src/main/resources/secret.env
